Models/Society_Add.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingSociety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Society_Add
    {
        public int REGID { get; set; }
        public string POST { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Wing { get; set; }
        public string Flat_No { get; set; }
        public string Time_From { get; set; }
        public string Time_To { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

Controllers/Society_AddController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using HousingSociety.Models;

namespace HousingSociety.Controllers
{
    public class Society_AddController : Controller
    {
        private Society_AddEnitites db = new Society_AddEnitites();

        // GET: Society_Add
        public ActionResult Index()
        {
            return View(db.Society_Add.ToList());
        }

        // GET: Society_Add/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Society_Add society_Add = db.Society_Add.Find(id);
            if (society_Add == null)
            {
                return HttpNotFound();
            }
            return View(society_Add);
        }

        // GET: Society_Add/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Society_Add/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "REGID,POST,Fname,Lname,Wing,Flat_No,Time_From,Time_To,Email,Password")] Society_Add society_Add)
        {
            if (ModelState.IsValid)
            {
                db.Society_Add.Add(society_Add);
                db.SaveChanges();
                //return RedirectToAction("Index");
                // ScriptManager.RegisterClientScriptBlock(this, this.GetType(), "alertMessage", "alert('Society Register Successfully')", true);
                
                return RedirectToAction("Admin_Home", "Login_Admin");
            }

            return View(society_Add);
        }

        // GET: Society_Add/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Society_Add society_Add = db.Society_Add.Find(id);
            if (society_Add == null)
            {
                return HttpNotFound();
            }
            return View(society_Add);
        }

        // POST: Society_Add/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "REGID,POST,Fname,Lname,Wing,Flat_No,Time_From,Time_To,Email,Password")] Society_Add society_Add)
        {
            if (ModelState.IsValid)
            {
                db.Entry(society_Add).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(society_Add);
        }

        // GET: Society_Add/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Society_Add society_Add = db.Society_Add.Find(id);
            if (society_Add == null)
            {
                return HttpNotFound();
            }
            return View(society_Add);
        }

        // POST: Society_Add/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Society_Add society_Add = db.Society_Add.Find(id);
            db.Society_Add.Remove(society_Add);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Society_Add/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<h2>Contact</h2>


<address>
    <strong>
        DAC21 :  HARSHAD NANNAWARE<br />
        <abbr title="Phone">Mobile :</abbr>
        +91 95790 55804 <br />
        <abbr title="Email">Email :</abbr>
        <a href="mailto:harshadnannaware007@gmail.com">harshadnannaware007@gmail.com</a>
    </strong>
</address>


<address>
    <strong>
        DAC22 :  HARSHAL UPASANI<br />
        <abbr title="Phone">Mobile :</abbr>
        +91 75071 68772 <br />
        <abbr title="Email">Email :</abbr>
        <a href="mailto:er.harshalupasani@gmail.com">er.harshalupasani@gmail.com</a>
    </strong>
</address>

<address>
    <strong>
        DAC23 :  HARSHAL PAYGHAN<br />
        <abbr title="Phone">Mobile :</abbr>
        +91 95790 55804 <br />
        <abbr title="Email">Email :</abbr>
        <a href="mailto:harshadnannaware007@gmail.com">harshadnannaware007@gmail.com</a>
    </strong>
</address>

<address>
    <strong>
        DAC24 :  HARSHALI BHANGALE<br />
        <abbr title="Phone">Mobile :</abbr>
        +91 90909 09090 <br />
        <abbr title="Email">Email :</abbr>
        <a href="mailto:harshalibhangale22@gmail.com">harshalibhangale22@gmail.com</a>
    </strong>
</address>

<address>
    <strong>
        DAC21 :  INKESH CHOUDHARY<br />
        <abbr title="Phone">Mobile :</abbr>
        +91 91919 19191 <br />
        <abbr title="Email">Email :</abbr>
        <a href="mailto:inkeshchoudhary@gmail.com">inkeshchoudhary@gmail.com</a>
    </strong>
</address>

Views/Society_Add/Create.cshtml
@model HousingSociety.Models.Society_Add

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<h2>Register Society</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Please Enter Society Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.POST, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.POST, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.POST, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Wing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Wing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Wing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Flat_No, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Flat_No, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Flat_No, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time_From, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time_From, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time_From, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time_To, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time_To, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time_To, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="reset" value="Reset" class="btn btn-default" />
                
                <input type="submit" value="Register" class="btn btn-default" />
            </div>

        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
</div>

Views/Society_Add/Delete.cshtml
@model HousingSociety.Models.Society_Add

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<h2>Remove Society</h2>

<h3>To Permanent Delete this Society Click on Delete Button.</h3>
<div>
    @*<h4>Society_Add</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.REGID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.REGID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.POST)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.POST)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wing)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wing)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flat_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flat_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time_From)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time_From)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time_To)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time_To)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">

        @*@Html.ActionLink("Back to List", "Index")*@
        @Html.ActionLink("Back to Society Modify", "Index", "Society_Add")  |
        <input type="submit" value="Delete" class="btn btn-default" />
    </div>
    }
</div>

Views/Society_Add/Details.cshtml
@model HousingSociety.Models.Society_Add

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<h2>Society Details</h2>

<div>
    @*<h4>Society_Add</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.REGID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.REGID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.POST)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.POST)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wing)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wing)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flat_No)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flat_No)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time_From)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time_From)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time_To)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time_To)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to Society Modify", "Index", "Society_Add")  |
    @Html.ActionLink("UPDATE", "Edit", new { id = Model.Email }) 
    @*@Html.ActionLink("Back to List", "Index")*@
</p>

Views/Society_Add/Edit.cshtml
@model HousingSociety.Models.Society_Add

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<h2>Update Society</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Please make changes and click on Update Button</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.REGID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.REGID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.REGID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.POST, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.POST, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.POST, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Wing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Wing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Wing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Flat_No, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Flat_No, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Flat_No, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time_From, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time_From, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time_From, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time_To, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time_To, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time_To, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.Email)

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="UPDATE" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Back to Society Modify", "Index", "Society_Add")
        @*@Html.ActionLink("Back to List", "Index")*@
    </div>

Views/Society_Add/Index.cshtml
@model IEnumerable<HousingSociety.Models.Society_Add>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<h2>Society User Details</h2>

<p>
  @*  @Html.ActionLink("Register Society", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.REGID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.POST)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Wing)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Flat_No)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time_From)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time_To)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.REGID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.POST)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Wing)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Flat_No)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time_From)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time_To)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        @*<td>
            @Html.ActionLink("UPDATE", "Edit", new { id=item.Email }) |
            @Html.ActionLink("VIEW", "Details", new { id=item.Email }) |
            @Html.ActionLink("DELETE", "Delete", new { id=item.Email })
        </td>*@
    </tr>
}

</table>